---
proxy-providers:
  GAMING:
    type: file
    path: "./proxy_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  SOSMED:
    type: file
    path: "./proxy_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  STREAMING:
    type: file
    path: "./proxy_provider/streaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  PUBLIC:
    type: file
    path: "./proxy_provider/public.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  IDN:
    type: file
    path: "./proxy_provider/idn.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
proxy-groups:
- name: GAMING
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - GAMING
  url: http://www.gstatic.com/generate_204
  interval: '600'
  tolerance: '50'
- name: SOSMED
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - SOSMED
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: STREAMING
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - STREAMING
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: IDN
  type: fallback
  disable-udp: false
  use:
  - IDN
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PUBLIC
  type: fallback
  disable-udp: false
  use:
  - PUBLIC
  url: http://www.gstatic.com/generate_204
  interval: '300'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  system-dns: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  default-nameserver:
  - 162.159.36.1
  - 162.159.46.1
  - 192.168.8.1
  - 114.114.114.114
  - 119.29.29.29
  nameserver:
  - dhcp://"eth1"
  - 192.168.8.1
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
tproxy-port: 7895
rule-providers:
  rule_direct:
    type: file
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_videoconferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_videoconferences.yaml
    interval: 86400
  rule_idn:
    type: http
    behavior: classical
    path: "./rule_provider/rule_idn.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_Indo.yaml
    interval: 86400
  rule_sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_sosmed.yaml
    interval: 86400
  rule_streaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_streaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_streaming.yaml
    interval: 86400
  rule_gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_speedtest:
    type: http
    behavior: domain
    url: https://rules.kr328.app/speedtest.yaml
    path: "./rule_provider/rule_speedtest.yaml"
    interval: 86400
  rule_discord:
    type: http
    behavior: domain
    url: https://rules.kr328.app/discord.yaml
    path: "./rule_provider/rule_discord.yaml"
    interval: 86400
  rule_reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./rule_provider/rule_reject.yaml"
    interval: 86400
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: "./rule_provider/rule_telegramcidr.yaml"
    interval: 86400
  rule_telegram:
    type: http
    behavior: domain
    url: https://rules.kr328.app/telegram.yaml
    path: "./rule_provider/rule_telegram.yaml"
    interval: 86400
  rule_disneyplus:
    type: http
    behavior: domain
    url: https://rules.kr328.app/disney.yaml
    path: "./rule_provider/rule_disneyplus.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://rules.kr328.app/category-games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400
  rule_hbo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/hbo.yaml
    path: "./rule_provider/rule_hbo.yaml"
    interval: 86400
  rule_iqiyi:
    type: http
    behavior: domain
    url: https://rules.kr328.app/iqiyi.yaml
    path: "./rule_provider/rule_iqiyi.yaml"
    interval: 86400
  rule_line:
    type: http
    behavior: domain
    url: https://rules.kr328.app/line.yaml
    path: "./rule_provider/rule_line.yaml"
    interval: 86400
  rule_netflix:
    type: http
    behavior: domain
    url: https://rules.kr328.app/netflix.yaml
    path: "./rule_provider/rule_netflix.yaml"
    interval: 86400
  rule_primevideo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/primevideo.yaml
    path: "./rule_provider/rule_primevideo.yaml"
    interval: 86400
  rule_playstore:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400
  rule_tiktok:
    type: http
    behavior: domain
    url: https://rules.kr328.app/tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400
  rule_twitch:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitch.yaml
    path: "./rule_provider/rule_twitch.yaml"
    interval: 86400
  rule_twitter:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400
  rule_youtube:
    type: http
    behavior: domain
    url: https://rules.kr328.app/youtube.yaml
    path: "./rule_provider/rule_youtube.yaml"
    interval: 86400
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,22,DIRECT
- RULE-SET,rule_reject,REJECT
- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_direct,DIRECT
- RULE-SET,rule_speedtest,PUBLIC
- RULE-SET,rule_streaming,STREAMING
- RULE-SET,rule_disneyplus,STREAMING
- RULE-SET,rule_hbo,STREAMING
- RULE-SET,rule_iqiyi,STREAMING
- RULE-SET,rule_netflix,STREAMING
- RULE-SET,rule_primevideo,STREAMING
- RULE-SET,rule_twitch,STREAMING
- RULE-SET,rule_youtube,STREAMING
- RULE-SET,rule_sosmed,SOSMED
- RULE-SET,rule_line,SOSMED
- RULE-SET,rule_tiktok,SOSMED
- RULE-SET,rule_twitter,SOSMED
- RULE-SET,rule_telegram,SOSMED
- RULE-SET,rule_telegramcidr,SOSMED
- RULE-SET,rule_gaming,GAMING
- RULE-SET,rule_discord,GAMING
- RULE-SET,rule_games,GAMING
- RULE-SET,rule_portgames,GAMING
- RULE-SET,rule_videoconferences,STREAMING
- RULE-SET,rule_playstore,PUBLIC
- RULE-SET,rule_idn,IDN
- DST-PORT,21,GLOBAL
- DST-PORT,23,GLOBAL
- DST-PORT,25,GLOBAL
- DST-PORT,80,GLOBAL
- DST-PORT,81,GLOBAL
- DST-PORT,143,GLOBAL
- DST-PORT,443,GLOBAL
- DST-PORT,465,GLOBAL
- DST-PORT,587,GLOBAL
- DST-PORT,993,GLOBAL
- DST-PORT,995,GLOBAL
- DST-PORT,8000,GLOBAL
- DST-PORT,8008,GLOBAL
- DST-PORT,8080,GLOBAL
- DST-PORT,8081,GLOBAL
- DST-PORT,8090,GLOBAL
- DST-PORT,8443,GLOBAL
- DST-PORT,8888,GLOBAL
- MATCH,GLOBAL
ipv6: false
geodata-mode: false
geodata-loader: memconservative
tcp-concurrent: true
sniffer:
  enable: true
  sniffing:
  - tls
  - http
profile:
  store-selected: true
  store-fake-ip: true
